### ISSUE TITLE
No products found!

### ISSUE THREAD

**Issue by laportem** [DivanteLtd/vue-storefront-api#178] opened 2019-01-27 22:09 UTC
I’ve been trying to sync data from magneto (CE version 2.3) to VS (release 1.7.0) and for some reasons the Products are not showing up on the screen 

**Categories are visible in the UI but not Products**

I’ve tried both the “Fast integration” and “Manual integration” described in @ [(https://docs.vuestorefront.io/guide/installation/magento.html#integrating-magento2-with-your-local-instance)]

I did not get any errors and checking my ES, I get see that “category” and “product” are in ES
`curl -XPOST 'localhost:9200/vue_storefront_catalog/category/_search'`
`curl -XPOST 'localhost:9200/vue_storefront_catalog/product/_search'`

Any pointers as to why the Products are not showing up when I click on the appropriate Category in VS frontend. BTW, It works ok on the default Magento frontend. Ruled out product setup issue in Magento

`curl -XPOST 'localhost:9200/vue_storefront_catalog/product/_search'`

`
{"took":1,"timed_out":false,"_shards":{"total":5,"successful":5,"skipped":0,"failed":0},"hits":{"total":4,"max_score":1.0,"hits":[{"_index":"vue_storefront_catalog_1548591100","_type":"product","_id":"12","_score":1.0,"_source":{"id":12,"sku":"cavendish_banana","name":"Cavendish Banana","attribute_set_id":4,"price":20,"status":1,"visibility":4,"type_id":"simple","created_at":"2019-01-25 18:26:53","updated_at":"2019-01-27 13:16:58","extension_attributes":{"website_ids":[1],"category_links":[{"category_id":"7","position":10}]},"product_links":[],"options":[],"media_gallery_entries":[{"types":["image","small_image","thumbnail","swatch_image"],"file":"/c/a/cavendish_bananas.jpeg","media_type":"image","disabled":false,"id":5,"label":null,"position":1}],"tier_prices":[],"custom_attributes":null,"final_price":20,"max_price":20,"max_regular_price":20,"minimal_regular_price":20,"special_price":null,"minimal_price":20,"regular_price":20,"image":"/c/a/cavendish_bananas.jpeg","small_image":"/c/a/cavendish_bananas.jpeg","thumbnail":"/c/a/cavendish_bananas.jpeg","swatch_image":"/c/a/cavendish_bananas.jpeg","options_container":"container2","url_key":"cavendish-banana","gift_message_available":"2","required_options":"0","has_options":"0","meta_title":"Cavendish Banana","meta_keyword":"Cavendish Banana","meta_description":"Cavendish Banana This one is good 1","tax_class_id":"0","category_ids":["7"],"description":"<p>This one is good 1</p>","short_description":"<p>This one is good 2</p>","country_of_manufacture":"SC","size":"4","links":{},"stock":{"item_id":20,"product_id":12,"stock_id":1,"qty":0,"is_in_stock":false,"is_qty_decimal":false,"show_default_notification_message":false,"use_config_min_qty":true,"min_qty":0,"use_config_min_sale_qty":1,"min_sale_qty":1,"use_config_max_sale_qty":true,"max_sale_qty":10000,"use_config_backorders":true,"backorders":0,"use_config_notify_stock_qty":true,"notify_stock_qty":1,"use_config_qty_increments":true,"qty_increments":0,"use_config_enable_qty_inc":true,"enable_qty_increments":false,"use_config_manage_stock":true,"manage_stock":true,"low_stock_date":"2019-01-27 13:16:58","is_decimal_divided":false,"stock_status_changed_auto":1},"media_gallery":[{"image":"/c/a/cavendish_bananas.jpeg","pos":1,"typ":"image","lab":null}],"category":[{"category_id":7,"name":"Bananas"}],"tsk":1548623855015}},{"_index":"vue_storefront_catalog_1548591100","_type":"product","_id":"15","_score":1.0,"_source":{"id":15,"sku":"danvers_carrots_jojo","name":"Danvers Carrots","attribute_set_id":4,"price":12,"status":1,"visibility":4,"type_id":"simple","created_at":"2019-01-27 11:29:36","updated_at":"2019-01-27 11:43:40","extension_attributes":{"website_ids":[1],"category_links":[{"category_id":"9","position":0}]},"product_links":[],"options":[],"media_gallery_entries":[],"tier_prices":[],"custom_attributes":null,"final_price":12,"max_price":12,"max_regular_price":12,"minimal_regular_price":12,"special_price":null,"minimal_price":12,"regular_price":12,"options_container":"container2","url_key":"danvers-carrots","gift_message_available":"2","required_options":"0","has_options":"0","meta_title":"Danvers Carrots","meta_keyword":"Danvers Carrots","meta_description":"Danvers Carrots ","tax_class_id":"0","category_ids":["9"],"links":{},"stock":{"item_id":23,"product_id":15,"stock_id":1,"qty":0,"is_in_stock":false,"is_qty_decimal":false,"show_default_notification_message":false,"use_config_min_qty":true,"min_qty":0,"use_config_min_sale_qty":1,"min_sale_qty":1,"use_config_max_sale_qty":true,"max_sale_qty":10000,"use_config_backorders":true,"backorders":0,"use_config_notify_stock_qty":true,"notify_stock_qty":1,"use_config_qty_increments":true,"qty_increments":0,"use_config_enable_qty_inc":true,"enable_qty_increments":false,"use_config_manage_stock":true,"manage_stock":true,"low_stock_date":"2019-01-27 11:43:40","is_decimal_divided":false,"stock_status_changed_auto":1},"media_gallery":[],"category":[{"category_id":9,"name":"Carrots"}],"tsk":1548623855015}},{"_index":"vue_storefront_catalog_1548591100","_type":"product","_id":"16","_score":1.0,"_source":{"id":16,"sku":"Simple Banana","name":"Simple Banana","attribute_set_id":4,"price":121,"status":1,"visibility":4,"type_id":"simple","created_at":"2019-01-27 20:40:40","updated_at":"2019-01-27 20:41:02","extension_attributes":{"website_ids":[1],"category_links":[{"category_id":"7","position":0}]},"product_links":[],"options":[],"media_gallery_entries":[],"tier_prices":[],"custom_attributes":null,"options_container":"container2","url_key":"simple-banana","gift_message_available":"2","required_options":"0","has_options":"0","meta_title":"Simple Banana","meta_keyword":"Simple Banana","meta_description":"Simple Banana ","tax_class_id":"0","category_ids":["7"],"country_of_manufacture":"SC","size":"4","links":{},"stock":{"item_id":24,"product_id":16,"stock_id":1,"qty":0,"is_in_stock":false,"is_qty_decimal":false,"show_default_notification_message":false,"use_config_min_qty":true,"min_qty":0,"use_config_min_sale_qty":1,"min_sale_qty":1,"use_config_max_sale_qty":true,"max_sale_qty":10000,"use_config_backorders":true,"backorders":0,"use_config_notify_stock_qty":true,"notify_stock_qty":1,"use_config_qty_increments":true,"qty_increments":0,"use_config_enable_qty_inc":true,"enable_qty_increments":false,"use_config_manage_stock":true,"manage_stock":true,"low_stock_date":"2019-01-27 20:41:02","is_decimal_divided":false,"stock_status_changed_auto":1},"media_gallery":[],"category":[{"category_id":7,"name":"Bananas"}],"tsk":1548623855015}},{"_index":"vue_storefront_catalog_1548591100","_type":"product","_id":"13","_score":1.0,"_source":{"id":13,"sku":"burro_banana","name":"Burro Banana","attribute_set_id":4,"price":10,"status":1,"visibility":4,"type_id":"simple","created_at":"2019-01-25 18:39:33","updated_at":"2019-01-27 11:42:41","extension_attributes":{"website_ids":[1],"category_links":[{"category_id":"7","position":0}]},"product_links":[],"options":[],"media_gallery_entries":[{"types":["image","small_image","thumbnail","swatch_image"],"file":"/b/u/burro_bananas-1.jpg","media_type":"image","disabled":false,"id":6,"label":null,"position":1}],"tier_prices":[],"custom_attributes":null,"final_price":10,"max_price":10,"max_regular_price":10,"minimal_regular_price":10,"special_price":null,"minimal_price":10,"regular_price":10,"image":"/b/u/burro_bananas-1.jpg","small_image":"/b/u/burro_bananas-1.jpg","thumbnail":"/b/u/burro_bananas-1.jpg","swatch_image":"/b/u/burro_bananas-1.jpg","options_container":"container2","url_key":"burro-banana","gift_message_available":"2","required_options":"0","has_options":"0","meta_title":"Burro Banana","meta_keyword":"Burro Banana","meta_description":"Burro Banana ddddddd","tax_class_id":"0","category_ids":["7"],"description":"<p>ddddddd</p>","short_description":"<p>eeeeeeeeeeee</p>","links":{},"stock":{"item_id":21,"product_id":13,"stock_id":1,"qty":0,"is_in_stock":false,"is_qty_decimal":false,"show_default_notification_message":false,"use_config_min_qty":true,"min_qty":0,"use_config_min_sale_qty":1,"min_sale_qty":1,"use_config_max_sale_qty":true,"max_sale_qty":10000,"use_config_backorders":true,"backorders":0,"use_config_notify_stock_qty":true,"notify_stock_qty":1,"use_config_qty_increments":true,"qty_increments":0,"use_config_enable_qty_inc":true,"enable_qty_increments":false,"use_config_manage_stock":true,"manage_stock":true,"low_stock_date":"2019-01-27 11:42:41","is_decimal_divided":false,"stock_status_changed_auto":1},"media_gallery":[{"image":"/b/u/burro_bananas-1.jpg","pos":1,"typ":"image","lab":null}],"category":[{"category_id":7,"name":"Bananas"}],"tsk":1548623855015}}]}}
vagrant@vuestorefront:~/storefront-api$
`

**Comment by pkarw** [comment] 2019-02-11 15:00
Duplicate of https://github.com/DivanteLtd/vue-storefront/issues/2295

**Closed by pkarw** 2019-02-11 15:00 UTC
